### ISSUE TITLE
Thanks, and general issues

### ISSUE THREAD

**Issue by tsalex1992** [tsvi/Specman#1]
Hello Tsvi, first of all thank you for your great work. Your syntax really helps me in my work. I really wanted to use a modern text editor with specman and you made that possible.
I would like to point out a few issues that I have though:
1) I can't make a comment block, for some reason the ctrl / combination and going to edit and selecting the block comment won't work. So for now I have to manually comment each line.
2)The syntax sometimes is inconsistent for example:
        ListOfUintToListOfBytes(input : list of uint(bits:64)) :list of byte is also{
            var output : list of byte ;
            messagef(MEDIUM, "Alex inside uint to bytes function got this as input %s  \n",input) ;

            for each uint(bits:64) (n) in input {
            	messagef(MEDIUM, "Alex inside uint to bytes function adding uint (not as a byte yet) %s to output \n",n) ;
                output.add(BusToListOfBytes(n,8));

            };
            return output;
        };
The second messagef function is highlighted (in lime) and and the first one isn't.
I have other syntax highlighting inconsistencies with comment blocks or function calls. (I'll point them out if you'd like). Thanks ,Alex.

**Comment by tsvi** [comment]
Hi @tsalex1992 a lot of fixes were incorporated by @blutsvente. Could you check if these issues still exist?

**Comment by damnsavage** [comment]
Hi Tsvi,

I just started using sublime text 3 and it's great to have some syntax highlighting for e code, so thank you! I see the same problem that tsalex reported regarding the comment block 'ctrl +/', no comments are added or removed.

When I go to a commented line and type 'shift + ctrl + alt + p' I can see that comments are correctly detected.

Also enabling the console with > sublime.log_commands(True) 
The console prints out the message: command: toggle_comment {"block": false}
when I type 'ctrl +/' so the key bindings seem ok.

I don't know the next step though who picks up this toggle_comment command 
and performs an action...?

There's is no toggle_comment context in the SpecmanCode.sublime-syntax file,
but there's also none in a systemverilog syntax file and that one works ok...

Best regards

Damian

**Comment by blutsvente** [comment]
Hi @damnsavage ,

thanks for pointing this out. The toggle-comment needs a .tmPreferences file, see https://forum.sublimetext.com/t/toggle-comment-with-a-custom-sublime-syntax/18789/3
I created one and saved it as Specman.tmPreferences in the Packages/User folder.

I could not post the source-code, so I uploaded it to https://github.com/blutsvente/Specman .

This works for me, could you try that?
/Thorsten.

**Comment by damnsavage** [comment]
Hi @blutsvente 

Thanks that works for me!
I see you've made other updates too, I appreciate it.
I've been trying to understand that sublime syntax file, it takes a bit of work...

Best regards

Damian

**Comment by tsvi** [comment]
Closing this issue via PR #4 

If issues are found, please open one for every bug. Thanks.
